apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
    - name: frontend
      image: anandnandhu/frontend
---
apiVersion: v1
kind: Pod
metadata:
  name: cart
spec:
  containers:
    - name: cart
      image: anandnandhu/cart
---
apiVersion: v1
kind: Pod
metadata:
  name: catalogue
spec:
  containers:
    - name: catalouge
      image: anandnandhu/catalogue
---
apiVersion: v1
kind: Pod
metadata:
  name: user
spec:
  containers:
    - name: user
      image: anandnandhu/user
---
apiVersion: v1
kind: Pod
metadata:
  name: payment
spec:
  containers:
    - name: payment
      image: anandnandhu/payment
---
apiVersion: v1
kind: Pod
metadata:
  name: shipping
spec:
  containers:
    - name: shipping
      image: anandnandhu/shipping
